module.exports.descriptors=[
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Mapple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places=[
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse camp',
    'Gost town',
    'Camp',
    'Dispersed camp',
    'Backcountry',
    'River',
    'creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'hunting Camp',
    'Cliffs',
    'hollow'
]